id: AE818C024
title: Brief Offering Prayer to Mahādeva and Consort
type: translation
pechas:
- I9D044587
- IFC995486
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:06:18.409950
  last_modified_at: 2023-01-04 13:06:18.409958
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I9D044587/4613: 334D
  IFC995486/B44A: 334D
